version: '3'
services:
  mongo:
    container_name: mongo_container
    image: mongo:5
    restart: always
    volumes:
      - ./data:/data/db
    ports:
        - "27018:27017"
  api:
    container_name: api_container
    build: .
    image: clean-node-api
    restart: always
    command: npm run debug
    volumes:
     - ./dist:/usr/src/clean-node-api/dist
     - ./package.json:/usr/src/clean-node-api/package.json
    ports: 
     - "5050:5050"
     - "9222:9222"
    links:
     - mongo